forever stop -c python3.8 main.py
forever stop -c python3.8 bot2.py
forever stop -c python3.8 bot3.py
forever stop -c python3.8 bot4.py
forever stop -c python3.8 bot5.py
forever stop -c python3.8 bot6.py
forever stop -c python3.8 bot7.py
forever stop -c python3.8 bot8.py
forever stop -c python3.8 bot9.py
forever stop -c python3.8 bot10.py
